[toolchain]
# The default profile includes rustc, rust-std, cargo, rust-docs, rustfmt and clippy.
# https://rust-lang.github.io/rustup/concepts/profiles.html
# profile = "default"
# channel = "stable"

# Find versions: https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2022-02-23"
components = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "miri",
  "reproducible-artifacts",
  "rls",
  "rust-analysis",
  "rust-analyzer-preview",
  "rust-docs",
  "rust-std",
  "rustc",
  "rustc-dev",
  "rustc-docs",
  "rustfmt",
]
