[package]
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"
name = "skribble_css"
version = "0.0.0"

[lib]
crate-type = ["lib"]

[dependencies]
colorsys = "^0.6.5"
easy-error = "^1.0.0"
heck = "^0.4.0"
indexmap = { features = ["serde"], version = "^1.8.0" }
indoc = "^1.0.3"
readonly = "^0.2.0"
regex = "^1.5.4"
serde = "^1.0.136"
serde_json = "^1.0.78"
swc_atoms = "^0.2.9"
swc_common = "^0.17.2"
swc_ecma_minifier = "^0.71.4"
swc_ecmascript = { features = ["utils", "visit", "parser"], version = "^0.111.9" }

[dev-dependencies]
testing = "0.18.0"
walkdir = "2.3.2"
pretty_assertions = "1.0.0"
insta = "1.12.0"

