[toolchain]
# The default profile includes rustc, rust-std, cargo, rust-docs, rustfmt and clippy.
# https://rust-lang.github.io/rustup/concepts/profiles.html
# profile = "default"
# channel = "stable"

# Find versions: https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2022-04-13"
profile = "default"
