import type { SkribbleConfig } from './config-types.js';
import { PALETTE } from './palette';

export const DEFAULT_CONFIG: SkribbleConfig = {
  options: {
    colorFormat: 'rgb',
  },
  keyframes: {
    enter: {
      from: {
        opacity: 'var(--sk-enter-opacity, 1)',
        transform:
          'translate3d(var(--sk-enter-translate-x, 0), var(--sk-enter-translate-y, 0), 0) scale3d(var(--sk-enter-scale, 1), var(--sk-enter-scale, 1), var(--sk-enter-scale, 1)) rotate(var(--sk-enter-rotate, 0))',
      },
    },
    exit: {
      to: {
        opacity: 'var(--sk-exit-opacity, 1)',
        transform:
          'translate3d(var(--sk-exit-translate-x, 0), var(--sk-exit-translate-y, 0), 0) scale3d(var(--sk-exit-scale, 1), var(--sk-exit-scale, 1), var(--sk-exit-scale, 1)) rotate(var(--sk-exit-rotate, 0))',
      },
    },
    spin: { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
    ping: { '75%, 100%': { transform: 'scale(2)', opacity: '0' } },
    pulse: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
    bounce: {
      '0%, 100%': {
        transform: 'translateY(-25%)',
        animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)',
      },
      '50%': {
        transform: 'translateY(0)',
        animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
      },
    },
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    xxl: '1536px',
  },
  mediaQueries: {
    print: 'print',
    portrait: '(orientation: portrait)',
    landscape: '(orientation: landscape)',
    darkScheme: '(prefers-color-scheme: dark)',
    lightScheme: '(prefers-color-scheme: light)',
    motionSafe: '(prefers-reduced-motion: no-preference)',
    motionReduce: '(prefers-reduced-motion: reduce)',
  },
  parentModifiers: {
    light: ['.light &'],
    dark: ['.dark &'],
    rtl: ['[dir=rtl] &'],
    groupHover: ['.\\$group:hover &', '.group:hover &', "[role='group']:hover &"],
    groupFocus: ['.\\$group:focus &', '.group:focus &', "[role='group']:focus &"],
    groupActive: ['.\\$group:active &', '.group:active &', "[role='group']:active &"],
    groupVisited: ['.\\$group:visited &', '.group:visited &', "[role='group']:visited &"],
  },
  modifiers: [
    { hover: ['&:hover'] },
    { active: ['&:active'] },
    { focus: ['&:focus'] },
    { focusWithin: ['&:focus-within'] },
    { focusVisible: ['&:focus-visible'] },
    {
      disabled: ['&[disabled]', '&[aria-disabled=true]', '&:disabled'],
      notDisabled: ['&[aria-disabled=false]', '&:disabled'],
      enabled: ['&:enabled'],
    },
    { empty: ['&:empty'] },
    {
      readWrite: ['&:read-write'],
      readOnly: ['&[aria-readonly=true]', '&[readonly]', '&:read-only'],
      notReadOnly: ['&[aria-readonly=false]', '&[readonly=false]', '&:not(:read-only)'],
    },
    { expanded: ['&[aria-expanded=true]'] },
    {
      indeterminate: ['&:indeterminate', '&[aria-checked=mixed]'],
      checked: ['&[aria-checked=true]', '&:checked'],
      unchecked: ['&[aria-checked=false]', '&:not(:checked)'],
    },
    { grabbed: ['&[aria-grabbed=true]'] },
    { pressed: ['&[aria-pressed=true]'] },
    { invalidGrammar: ['&[aria-invalid=grammar]'] },
    { invalidSpelling: ['&[aria-invalid=spelling]'] },
    {
      valid: ['&[aria-invalid=false]', '&:valid'],
      invalid: ['&[aria-invalid=true]', '&:invalid'],
    },
    { loading: ['&[aria-busy=true]'] },
    { selected: ['&[aria-selected=true]'] },
    { hidden: ['&[hidden]'] },
    { autofill: ['&:-webkit-autofill'] },
    { even: ['&:even'], odd: ['&:odd'] },
    { evenOfType: ['&:nth-of-type(even)'], oddOfType: ['&:nth-of-type(odd)'] },
    {
      first: ['&:first'],
      notFirst: ['&:not(:first-child)'],
      last: ['&:last'],
      notLast: ['&:not(:last-child)'],
    },
    {
      firstOfType: ['&:first-of-type'],
      notFirstOfType: ['&:not(:first-of-type)'],
      lastOfType: ['&:last-of-type'],
      notLastOfType: ['&:not(:last-of-type)'],
    },
    { visited: ['&:visited'] },
    { optional: ['&:optional'] },
    {
      activeLink: ['&[aria-current=page]'],
      activeLocation: ['&[aria-current=location]'],
      activeDate: ['&[aria-current=date]'],
      activeTime: ['&[aria-current=time]'],
      activeStep: ['&[aria-current=step]'],
    },
    { fullScreen: ['&:fullscreen'] },
    { target: ['&:target'] },
    { placeholderShown: ['&:placeholder-shown'] },
    {
      required: ['[aria-required=true]', '&:required'],
      notRequired: ['[arira-required=false]', '&:not(:required)'],
    },
    { default: ['&:default'] },
    {
      onlyChild: ['&:only-child'],
      notOnlyChild: ['&:not(:only-child)'],
    },
    {
      onlyOfType: ['&:only-of-type'],
      notOnlyOfType: ['&:not(:only-of-type)'],
    },
    { root: ['&:root'] },
    { link: ['&:link'] },
    {
      placeholder: ['&::placeholder'],
      selection: ['&::selection'],
      firstLetter: ['&::first-letter'],
      firstLine: ['&::first-line'],
      before: ['&::before'],
      after: ['&::after'],
    },
  ],
  colors: {
    primary: 'purple500',
    secondary: 'sky500',
    text: { selectors: { ':root': 'gray900', 'html.dark': 'gray50' } },
    background: { selectors: { ':root': 'gray50', 'html.dark': 'gray900' } },
    border: 'zinc400',
    media: {
      selectors: { ':root': 'zinc500' },
      mediaQueries: { print: { ':root': 'zinc900' } },
    },
  },
  variables: {
    '--sk-container-max-width': 'container',
    '--sk-custom-filter-roughen': `url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"><filter id="waves" x="-20%" y="-20%" width="140%" height="140%" filterUnits="objectBoundingBox" primitiveUnits="userSpaceOnUse" color-interpolation-filters="linearRGB"><feTurbulence type="turbulence" baseFrequency="0.01 0.01" numOctaves="1" seed="1" stitchTiles="noStitch" result="turbulence"/><feDisplacementMap in="SourceGraphic" in2="turbulence" scale="20" xChannelSelector="G" yChannelSelector="A"result="displacementMap"/></filter></svg>#waves')`,
    '--sk-filter-blur': ' ',
    '--sk-filter-brightness': ' ',
    '--sk-filter-contrast': ' ',
    '--sk-filter-custom': ' ',
    '--sk-filter-grayscale': ' ',
    '--sk-filter-hue-rotate': ' ',
    '--sk-filter-invert': ' ',
    '--sk-filter-saturate': ' ',
    '--sk-filter-sepia': ' ',
    '--sk-filter-drop-shadow': ' ',
    '--sk-group-nested-filter':
      'var(--sk-filter-blur) var(--sk-filter-brightness) var(--sk-filter-contrast) var(--sk-filter-grayscale) var(--sk-filter-hue-rotate) var(--sk-filter-invert) var(--sk-filter-saturate) var(--sk-filter-sepia) var(--sk-filter-drop-shadow) var(--sk-filter-custom)',
    '--sk-backdrop-blur': ' ',
    '--sk-backdrop-brightness': ' ',
    '--sk-backdrop-contrast': ' ',
    '--sk-backdrop-custom': ' ',
    '--sk-backdrop-grayscale': ' ',
    '--sk-backdrop-hue-rotate': ' ',
    '--sk-backdrop-invert': ' ',
    '--sk-backdrop-saturate': ' ',
    '--sk-backdrop-sepia': ' ',
    '--sk-backdrop-drop-shadow': ' ',
    '--sk-group-nested-backdrop':
      'var(--sk-backdrop-blur) var(--sk-backdrop-brightness) var(--sk-backdrop-contrast) var(--sk-backdrop-grayscale) var(--sk-backdrop-hue-rotate) var(--sk-backdrop-invert) var(--sk-backdrop-saturate) var(--sk-backdrop-sepia) var(--sk-backdrop-drop-shadow) var(--sk-backdrop-custom)',
    '--sk-transform-translate-x': ' ',
    '--sk-transform-translate-y': ' ',
    '--sk-transform-rotate': ' ',
    '--sk-transform-skew-x': ' ',
    '--sk-transform-skew-y': ' ',
    '--sk-transform-scale-x': ' ',
    '--sk-transform-scale-y': ' ',
    '--sk-group-nested-transform-gpu':
      'translate3d(var(--sk-transform-translate-x),var(--sk-transform-translate-y),0) rotate(var(--sk-transform-rotate)) skewX(var(--sk-transform-skew-x)) skewY(var(--sk-transform-skew-y)) scaleX(var(--sk-transform-scale-x)) scaleY(var(--sk-transform-scale-y))',
    '--sk-group-nested-transform-cpu':
      'translate(var(--sk-transform-translate-x),var(--sk-transform-translate-y),0) rotate(var(--sk-transform-rotate)) skewX(var(--sk-transform-skew-x)) skewY(var(--sk-transform-skew-y)) scaleX(var(--sk-transform-scale-x)) scaleY(var(--sk-transform-scale-y))',
    '--sk-group-nested-transform': 'var(--sk-group-nested-transform-cpu)',
    '--sk-default-transition-duration': '150ms',
    '--sk-default-animation-duration': '1s',
  },
  atoms: [
    {
      styleRules: ['sr'],
      values: {
        only: {
          position: 'absolute',
          width: '1px',
          height: '1px',
          padding: '0',
          margin: '-1px',
          overflow: 'hidden',
          clip: 'rect(0, 0, 0, 0)',
          whiteSpace: 'nowrap',
          borderWidth: '0',
        },
        exclude: {
          position: 'static',
          width: 'auto',
          height: 'auto',
          padding: '0',
          margin: '0',
          overflow: 'visible',
          clip: 'auto',
          whiteSpace: 'normal',
        },
      },
    },
    {
      styleRules: ['text'],
      colors: { opacity: '--sk-text-opacity', palette: true },
    },
    { styleRules: ['bg'], colors: { opacity: '--sk-bg-opacity', palette: true } },
    {
      styleRules: ['border'],
      colors: { opacity: '--sk-border-opacity', palette: true },
    },
    {
      styleRules: ['font'],
      values: {
        sans: 'ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"',
        serif: 'ui-serif,Georgia,Cambria,"Times New Roman",Times,serif',
        mono: 'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace',
      },
    },
    {
      styleRules: ['blur', 'backdropBlur'],
      groups: ['filter'],
      values: {
        none: 'blur(0)',
        sm: 'blur(4px)',
        '': 'blur(8px)',
        md: 'blur(12px)',
        lg: 'blur(16px)',
        xl: 'blur(24px)',
        '2xl': 'blur(40px)',
        '3xl': 'blur(64px)',
      },
    },
    {
      styleRules: ['brightness', 'backdropBrightness'],
      groups: ['filter'],
      values: {
        '0': 'brightness(0)',
        '50': 'brightness(.5)',
        '75': 'brightness(.75)',
        '90': 'brightness(.9)',
        '95': 'brightness(.95)',
        '100': 'brightness(1)',
        '105': 'brightness(1.05)',
        '110': 'brightness(1.1)',
        '125': 'brightness(1.25)',
        '150': 'brightness(1.5)',
        '200': 'brightness(2)',
      },
    },
    {
      styleRules: ['contrast', 'backdropContrast'],
      groups: ['filter'],
      values: {
        '0': 'contrast(0)',
        '50': 'contrast(.5)',
        '75': 'contrast(.75)',
        '100': 'contrast(1)',
        '125': 'contrast(1.25)',
        '150': 'contrast(1.5)',
        '200': 'contrast(2)',
      },
    },
    {
      styleRules: ['dropShadow', 'backdropDropShadow'],
      groups: ['filter'],
      values: {
        '': 'drop-shadow(0 1px 2px rgb(0 0 0 / 0.1)) drop-shadow(0 1px 1px rgb(0 0 0 / 0.06))',
        sm: 'drop-shadow(0 1px 1px rgb(0 0 0 / 0.05))',
        md: 'drop-shadow(0 4px 3px rgb(0 0 0 / 0.07)) drop-shadow(0 2px 2px rgb(0 0 0 / 0.06))',
        lg: 'drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1))',
        xl: 'drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08))',
        '2xl': 'drop-shadow(0 25px 25px rgb(0 0 0 / 0.15))',
        none: 'drop-shadow(0 0 #0000)',
      },
    },
    {
      styleRules: ['grayScale', 'backdropGrayScale'],
      groups: ['filter'],
      values: {
        '': 'grayscale(100%)',
        '0': 'grayscale(0)',
        '25': 'grayscale(25%)',
        '50': 'grayscale(50%)',
        '75': 'grayscale(75%)',
        '100': 'grayscale(100%)',
      },
    },
    {
      styleRules: ['hueRotate', 'backdropHueRotate'],
      groups: ['filter'],
      values: {
        '0': 'hue-rotate(0deg)',
        '15': 'hue-rotate(15deg)',
        '30': 'hue-rotate(30deg)',
        '60': 'hue-rotate(60deg)',
        '90': 'hue-rotate(90deg)',
        '180': 'hue-rotate(180deg)',
      },
    },
    {
      styleRules: ['invert', 'backdropInvert'],
      groups: ['filter'],
      values: {
        '': 'invert(100%)',
        '0': 'invert(0)',
        '100': 'invert(100%)',
      },
    },
    {
      styleRules: ['saturate', 'backdropSaturate'],
      groups: ['filter'],
      values: {
        '0': 'saturate(0)',
        '50': 'saturate(.5)',
        '100': 'saturate(1)',
        '150': 'saturate(1.5)',
        '200': 'saturate(2)',
      },
    },
    {
      styleRules: ['sepia', 'backdropSepia'],
      groups: ['filter'],
      values: {
        '': 'sepia(100%)',
        '0': 'sepia(0)',
        '100': 'sepia(100%)',
      },
    },
    {
      styleRules: ['filter', 'backdrop'],
      groups: ['filter'],
      values: {
        rough: 'var(--sk-custom-filter-roughen)',
      },
    },
    {
      styleRules: [
        'p',
        'py',
        'px',
        'pt',
        'pr',
        'pb',
        'pl',
        'pbl',
        'pin',
        'pins',
        'pine',
        'pbls',
        'pble',
        'm',
        'my',
        'mx',
        'mt',
        'mr',
        'mb',
        'ml',
      ],
      values: {
        '0': '0px',
        px: '1px',
        '0_5': '0.125rem',
        '1': '0.25rem',
        '1_5': '0.375rem',
        '2': '0.5rem',
        '2_5': '0.625rem',
        '3': '0.75rem',
        '3_5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
    },
    {
      styleRules: ['fontSize'],
      values: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
      },
    },
    {
      styleRules: ['lineHeight'],
      values: {
        xs: '0.75rem',
        sm: '1.25rem',
        base: '1.5rem',
        lg: '1.75rem',
        xl: '1.75rem',
        '2xl': '2rem',
        '3xl': '2.25rem',
        '4xl': '2.5rem',
        '5xl': '1',
        '6xl': '1',
        '7xl': '1',
        '8xl': '1',
      },
    },
    {
      styleRules: ['dir'],
      values: {
        ltr: 'ltr',
        rtl: 'rtl',
      },
    },
    {
      styleRules: ['display'],
      values: {
        block: 'block',
        inlineBlock: 'inline-block',
        inline: 'inline',
        flowRoot: 'flow-root',
        content: 'content',
        hidden: 'none',
        listItem: 'list-item',
      },
    },
    {
      styleRules: ['visibility'],
      values: {
        hide: 'hidden',
        show: 'visible',
      },
    },
    {
      styleRules: ['visibility'],
      values: {
        hide: 'hidden',
        show: 'visible',
      },
    },
    {
      styleRules: ['opacity', 'fade'],
      values: {
        '0': '0',
        '5': '5',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '60': '60',
        '70': '70',
        '75': '75',
        '80': '80',
        '90': '90',
        '95': '95',
        '100': '100',
      },
    },
    {
      styleRules: ['z'],
      values: {
        auto: 'auto',
        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '60': '60',
        _1: '-1',
        '-2': '-2',
        _3: '-3',
        _5: '-5',
      },
    },
    {
      styleRules: ['textOrientation'],
      values: {
        mixed: 'mixed',
        up: 'upright',
        s: 'sideways',
        sr: 'sideways-right',
        glyph: 'use-glyph-orientation',
        unset: 'unset',
      },
    },
    {
      styleRules: ['writingMode'],
      values: {
        htb: 'horizontal-tb',
        vrl: 'vertical-rl',
        vlr: 'vertical-lr',
        srl: 'sideways-rl',
        slr: 'sideways-lr',
        unset: 'unset',
      },
    },
    {
      styleRules: ['scale', 'scaleX', 'scaleY', 'zoom'],
      groups: ['transform'],
      values: {
        0: '0',
        50: '.5',
        75: '.75',
        90: '.9',
        95: '.95',
        100: '1',
        105: '1.05',
        110: '1.1',
        125: '1.25',
        150: '1.5',
      },
    },
    {
      styleRules: ['rotate', 'spin'],
      groups: ['transform'],
      values: {
        0: '0deg',
        1: '1deg',
        2: '2deg',
        3: '3deg',
        6: '6deg',
        12: '12deg',
        45: '45deg',
        90: '90deg',
        180: '180deg',
        270: '270deg',
        315: '315deg',
      },
    },
    {
      styleRules: ['skewX', 'skewY'],
      groups: ['transform'],
      values: {
        0: '0deg',
        1: '1deg',
        2: '2deg',
        3: '3deg',
        6: '6deg',
        12: '12deg',
      },
    },
    {
      styleRules: ['origin'],
      values: {
        center: 'center',
        top: 'top',
        topRight: 'top right',
        right: 'right',
        bottomRight: 'bottom right',
        bottom: 'bottom',
        bottomLeft: 'bottom left',
        left: 'left',
        topLeft: 'top left',
      },
    },
    {
      styleRules: ['translateX', 'translateY', 'slideBottom', 'slideRight'],
      values: {
        '0': '0px',
        px: '1px',
        '0_5': '0.125rem',
        '1': '0.25rem',
        '1_5': '0.375rem',
        '2': '0.5rem',
        '2_5': '0.625rem',
        '3': '0.75rem',
        '3_5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        '1of2': '50%',
        '1of3': '33.333333%',
        '2of3': '66.666667%',
        '1of4': '25%',
        '2of4': '50%',
        '3of4': '75%',
        full: '100%',
      },
    },
    {
      styleRules: ['translateX', 'translateY', 'slideTop', 'slideLeft'],
      values: {
        _px: '-1px',
        _0_5: '-0.125rem',
        _1: '-0.25rem',
        _1_5: '-0.375rem',
        _2: '-0.5rem',
        _2_5: '-0.625rem',
        _3: '-0.75rem',
        _3_5: '-0.875rem',
        _4: '-1rem',
        _5: '-1.25rem',
        _6: '-1.5rem',
        _7: '-1.75rem',
        _8: '-2rem',
        _9: '-2.25rem',
        _10: '-2.5rem',
        _11: '-2.75rem',
        _12: '-3rem',
        _14: '-3.5rem',
        _16: '-4rem',
        _20: '-5rem',
        _24: '-6rem',
        _28: '-7rem',
        _32: '-8rem',
        _36: '-9rem',
        _40: '-10rem',
        _44: '-11rem',
        _48: '-12rem',
        _52: '-13rem',
        _56: '-14rem',
        _60: '-15rem',
        _64: '-16rem',
        _72: '-18rem',
        _80: '-20rem',
        _96: '-24rem',
        _1of2: '-50%',
        _1of3: '-33.333333%',
        _2of3: '-66.666667%',
        _1of4: '-25%',
        _2of4: '-50%',
        _3of4: '-75%',
        _full: '-100%',
      },
    },
    {
      styleRules: ['transition'],
      values: {
        '': {
          transitionProperty:
            'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
        none: { transitionProperty: 'none' },
        all: {
          transitionProperty: 'all',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
        colors: {
          transitionProperty:
            'color, background-color, border-color, text-decoration-color, fill, stroke',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
        opacity: {
          transitionProperty: 'opacity',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
        shadow: {
          transitionProperty: 'box-shadow',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
        transform: {
          transitionProperty: 'transform',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: 'var(--sk-default-transition-duration)',
        },
      },
    },

    {
      styleRules: ['transitionProperty'],
      values: {
        '': 'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
        none: 'none',
        all: 'all',
        colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
        opacity: 'opacity',
        shadow: 'box-shadow',
        transform: 'transform',
      },
    },
    {
      styleRules: ['duration', 'delay', 'animationDelay', 'animationDuration'],
      values: {
        0: '0ms',
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
        1500: '1500ms',
        2000: '2000ms',
      },
    },
    {
      styleRules: ['ease', 'animationTiming'],
      values: {
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
    {
      styleRules: ['animate'],
      values: { none: 'none' },
    },
    {
      styleRules: ['animate'],
      keyframes: ['spin'],
      values: { spin: 'spin var(--sk-default-animation-duration) linear infinite' },
    },
    {
      styleRules: ['animate'],
      keyframes: ['ping'],
      values: {
        ping: 'ping var(--sk-default-animation-duration) cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
    {
      styleRules: ['animate'],
      keyframes: ['pulse'],
      values: {
        pulse:
          'pulse calc(2 * var(--sk-default-animation-duration)) cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
    {
      styleRules: ['animate'],
      keyframes: ['bounce'],
      values: { bounce: 'bounce var(--sk-default-animation-duration) infinite' },
    },
    {
      styleRules: ['animate'],
      keyframes: ['enter'],
      values: {
        in: {
          animation: 'enter var(--sk-default-animation-duration)',
          '--sk-enter-opacity': 'initial',
          '--sk-enter-scale': 'initial',
          '--sk-enter-rotate': 'initial',
          '--sk-enter-translate-x': 'initial',
          '--sk-enter-translate-y': 'initial',
        },
      },
    },
    {
      styleRules: ['animate'],
      keyframes: ['exit'],
      values: {
        out: {
          animation: 'exit var(--sk-default-animation-duration)',
          '--sk-exit-opacity': 'initial',
          '--sk-exit-scale': 'initial',
          '--sk-exit-rotate': 'initial',
          '--sk-exit-translate-x': 'initial',
          '--sk-exit-translate-y': 'initial',
        },
      },
    },
    {
      styleRules: ['animationState'],
      values: {
        running: 'running',
        paused: 'paused',
      },
    },
    {
      styleRules: ['animationFillMode'],
      values: {
        none: 'none',
        forwards: 'forwards',
        backwards: 'backwards',
        both: 'both',
      },
    },
    {
      styleRules: ['animationDirection'],
      values: {
        normal: 'normal',
        reverse: 'reverse',
        alt: 'alternate',
        altReverse: 'alternate-reverse',
      },
    },
    {
      styleRules: ['slideTop', 'slideLeft'],
      values: {
        '': '-100%',
      },
    },
    {
      styleRules: ['slideBottom', 'slideRight'],
      values: {
        '': '100%',
      },
    },
  ],
  styleRules: {
    sr: [],
    transition: ['transition'],
    transitionProperty: ['transition-property'],
    duration: ['transition-duration'],
    ease: ['transition-timing-function'],
    delay: ['transition-delay'],
    animate: ['animation'],
    animationDuration: ['animation-duration'],
    animationTiming: ['animation-timing-function'],
    animationDelay: ['animation-delay'],
    animationRepeat: ['animation-iteration-count'],
    animationDirection: ['animation-direction'],
    animationFillMode: ['animation-fill-mode'],
    animationState: ['animation-play-state'],
    fade: ['--sk-tw-enter-opacity'],
    animationTranslate: ['--sk-enter-translate'],
    spin: ['--sk-enter-rotate'],
    slideTop: ['--sk-enter-translate-y'],
    slideBottom: ['--sk-enter-translate-y'],
    slideLeft: ['--sk-enter-translate-x'],
    slideRight: ['--sk-enter-translate-x'],
    zoom: ['--sk-enter-scale'],
    font: ['font-family'],
    p: ['padding'],
    py: ['padding-top', 'padding-bottom'],
    px: ['padding-right', 'padding-left'],
    pt: ['padding-top'],
    pr: ['padding-right'],
    pb: ['padding-bottom'],
    pl: ['padding-left'],
    pbl: ['padding-block'],
    pbls: ['padding-block-start'],
    pble: ['padding-block-end'],
    pin: ['padding-inline'],
    pins: ['padding-inline-start'],
    pine: ['padding-inline-end'],
    m: ['margin'],
    my: ['margin-top', 'margin-bottom'],
    mx: ['margin-right', 'margin-left'],
    mt: ['margin-top'],
    mr: ['margin-right'],
    mb: ['margin-bottom'],
    ml: ['margin-left'],
    z: ['z-index'],
    dir: ['direction'],
    scale: ['--sk-transform-scale-x', '--sk-transform-scale-y'],
    scaleX: ['--sk-transform-scale-x'],
    scaleY: ['--sk-transform-scale-y'],
    rotate: ['--sk-transform-rotate'],
    translateX: ['--sk-transform-translate-x'],
    translateY: ['--sk-transform-translate-y'],
    skewX: ['--sk-transform-skew-x'],
    skewY: ['--sk-transform-skew-y'],
    origin: ['transform-origin'],
    blur: ['--sk-filter-blur'],
    brightness: ['--sk-filter-brightness'],
    contrast: ['--sk-filter-contrast'],
    grayscale: ['--sk-filter-grayscale'],
    hueRotate: ['--sk-filter-hue-rotate'],
    invert: ['--sk-filter-invert'],
    saturate: ['--sk-filter-saturate'],
    sepia: ['--sk-filter-sepia'],
    dropShadow: ['--sk-filter-drop-shadow'],
    filter: ['--sk-filter-custom'],
    backdropBlur: ['--sk-backdrop-blur'],
    backdropContrast: ['--sk-backdrop-contrast'],
    backdropGrayscale: ['--sk-backdrop-grayscale'],
    backdropHueRotate: ['--sk-backdrop-hue-rotate'],
    backdropInvert: ['--sk-backdrop-invert'],
    backdropSaturate: ['--sk-backdrop-saturate'],
    backdropSepia: ['--sk-backdrop-sepia'],
    backdropDropShadow: ['--sk-backdrop-drop-shadow'],
    backdrop: ['--sk-backdrop-custom'],
    backdropBrightness: ['--sk-backdrop-brightness'],
    backdropOpacity: ['--sk-backdrop-opacity'],
    text: [['--sk-text-opacity', 1], 'color'],
    fontSize: ['font-size'],
    lineHeight: ['line-height'],
    textOpacity: ['--sk-text-opacity'],
    textOrientation: ['text-orientation'],
    writingMode: ['writing-mode'],
    bg: [['--sk-bg-opacity', 1], 'color'],
    bgOpacity: ['--sk-bg-opacity'],
    opacity: ['opacity'],
  },
  shorthand: {
    group: [],
    container: [
      ['width', '100%'],
      ['max-width', 'var(--sk-container-max-width)'],
    ],
    italic: [['font-style', 'italic']],
    nonItalic: [['font-style', 'normal']],
    oblique: [['font-style', 'oblique -10deg']],
    antialiased: [
      ['-webkit-font-smoothing', 'antialiased'],
      ['-moz-osx-font-smoothing', 'grayscale'],
    ],
    subpixelAntialiased: [
      ['-webkit-font-smoothing', 'auto'],
      ['-moz-osx-font-smoothing', 'auto'],
    ],
    block: [['display', 'block']],
    inlineBlock: [['display', 'inline-block']],
    inline: [['display', 'inline']],
    flowRoot: [['display', 'flow-root']],
    content: [['display', 'content']],
    hidden: [['display', 'hidden']],
    invisible: [['visibility', 'hidden']],
    visible: [['visibility', 'visible']],
    removeFilter: [['--sk-group-nested-filter', 'none']],
    removeBackdrop: [['--sk-group-nested-backdrop', 'none']],
    transformGpu: [['--sk-group-nested-transform', 'var(--sk-group-nested-transform-gpu)']],
    transformCpu: [['--sk-group-nested-transform', 'var(--sk-group-nested-transform-cpu)']],
  },
  palette: PALETTE['tailwind'],
  groups: {
    transform: [['transform', 'var(--sk-group-nested-transform)']],
    filter: [['filter', 'var(--sk-group-nested-filter)']],
    backdrop: [['backdrop-filter', 'var(--sk-group-nested-backdrop)']],
  },
};
