import fs from 'node:fs/promises';
import { getBase } from './helpers';

function generateNamespace(content: string) {
  return `\
/**
 * Auto generated by \`generate-napi-types.ts\`
 *
 * Do not edit manually
 */

export declare namespace Bindings {
  ${content
    .split('\n')
    .filter(
      (line) =>
        ![
          '/* eslint-disable */',
          '/* tslint:disable */',
          '/* auto-generated by NAPI-RS */',
        ].includes(line.trim()),
    )
    .map((line) => (line.trim() ? `  ${line}` : ''))
    .join('\n')}
}`;
}

const TEMP_TSCONFIG = getBase('./packages/skribble-css/tmp.d.ts');
const OUTPUT_BINDINGS = getBase('./packages/skribble-css/src/bindings.ts');

async function main() {
  const contents = await fs.readFile(TEMP_TSCONFIG, 'utf8');
  await fs.writeFile(OUTPUT_BINDINGS, generateNamespace(contents));
}

main();
