/**
 * Auto generated by `generate-napi-types.ts`
 *
 * Do not edit manually
 */

export declare namespace Bindings {
  export function callThreadsafeFunction(callback: (...args: any[]) => any): void;
  export type JsSkribbleBridge = SkribbleBridge;
  export class SkribbleBridge {
    constructor();
    status(): number;
    addConfig(object: object): void;
    stringify(object: object): string;
    addExtensionHandler(name: string, callback: (...args: any[]) => any): void;
    callExtensionHandlers(callback: (...args: any[]) => any): object;
  }
}
