[package]
edition = "2021"
name = "skribble_css_node"
version = "0.0.0"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "^2.0.3"
napi-derive = "^2.0.7"
serde = "^1.0.136"
serde_json = "^1.0.78"
skribble_css = {path = "../skribble_css"}

[build-dependencies]
napi-build = "1.2.1"
