name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: '~/.pnpm-store'
  DEBUG: napi:*
  APP_NAME: skribble_css

jobs:
  # Lint the project
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm

      - name: check TS / JS files
        run: pnpm lint:es

      - name: check formatting
        run: pnpm lint:prettier

      - name: check repo and versions
        run: pnpm lint:repo

      - name: check build
        run: pnpm lint:build

  build-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm
        run: pnpm build:wasm

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: packages/skribble-css__core/packages/wasm/dist

  build_napi:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              pnpm run build:napi
              strip -x *.node
          - host: windows-latest
            build: pnpm run build:napi
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            build: |
              export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=32;
              export CARGO_PROFILE_RELEASE_LTO=false
              pnpm run build:napi
              # pnpm test
            target: i686-pc-windows-msvc
            setup: |
              choco install nodejs-lts --x86 -y --force
              echo "C:\Program Files (x86)\nodejs" >> $GITHUB_PATH
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            docker: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
              docker pull $DOCKER_REGISTRY_URL/napi-rs/napi-rs/nodejs-rust:lts-debian
              docker tag $DOCKER_REGISTRY_URL/napi-rs/napi-rs/nodejs-rust:lts-debian builder
            build: |
              docker run --rm -v ~/.cargo/git:/root/.cargo/git -v ~/.cargo/registry:/root/.cargo/registry -v $(pwd):/build -w /build builder pnpm run build:napi && strip skribble_css.linux-x64-gnu.node
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            docker: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
              docker pull $DOCKER_REGISTRY_URL/napi-rs/napi-rs/nodejs-rust:lts-alpine
              docker tag $DOCKER_REGISTRY_URL/napi-rs/napi-rs/nodejs-rust:lts-alpine builder
            build: docker run --rm -v ~/.cargo/git:/root/.cargo/git -v ~/.cargo/registry:/root/.cargo/registry -v $(pwd):/build -w /build builder pnpm run build:napi && strip skribble_css.linux-x64-musl.node
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              pnpm run build:napi --target=aarch64-apple-darwin
              strip -x *.node
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            setup: |
              sudo apt-get update
              sudo apt-get install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu -y
            build: |
              pnpm run build:napi --target=aarch64-unknown-linux-gnu
              aarch64-linux-gnu-strip skribble_css.linux-arm64-gnu.node
          - host: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
            build: |
              pnpm run build:napi --target=armv7-unknown-linux-gnueabihf
              arm-linux-gnueabihf-strip skribble_css.linux-arm-gnueabihf.node
          - host: ubuntu-20.04
            target: aarch64-linux-android
            build: |
              export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
              pnpm run build:napi --target aarch64-linux-android
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            downloadTarget: aarch64-unknown-linux-musl
            docker: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
              docker pull ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
              docker tag ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine builder
            build: |
              docker run --rm -v ~/.cargo/git:/root/.cargo/git -v ~/.cargo/registry:/root/.cargo/registry -v $(pwd):/build -w /build builder sh -c "pnpm run build:napi --target=aarch64-unknown-linux-musl && /aarch64-linux-musl-cross/bin/aarch64-linux-musl-strip skribble_css.linux-arm64-musl.node"
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: pnpm run build:napi --target aarch64-pc-windows-msvc

    name: 'build_napi:stable - ${{ matrix.settings.target }}'
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm

      - name: rust installation
        uses: ./.github/actions/rust
        with:
          target: ${{ matrix.settings.target }}

      - name: pull latest docker image
        if: ${{ matrix.settings.docker }}
        run: ${{ matrix.settings.docker }}
        env:
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

      - name: build native code
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.APP_NAME }}.*.node

  build_napi_freebsd:
    timeout-minutes: 15
    runs-on: macos-10.15
    name: 'build_napi:stable - freebsd'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build
        uses: vmactions/freebsd-vm@v0.1.5
        env:
          DEBUG: napi:*
          RUSTUP_HOME: /usr/local/rustup
          CARGO_HOME: /usr/local/cargo
          RUSTUP_IO_THREADS: 1
        with:
          envs: DEBUG RUSTUP_HOME CARGO_HOME RUSTUP_IO_THREADS
          usesh: true
          mem: 3000
          prepare: |
            pkg install -y curl node16 python2
            curl -qL https://www.npmjs.com/install.sh | sh
            npm install -g npm
            corepack enable
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal
            export PATH="/usr/local/cargo/bin:$PATH"
            echo "~~~~ rustc --version ~~~~"
            rustc --version
            echo "~~~~ node -v ~~~~"
            node -v
            echo "~~~~ pnpm --version ~~~~"
            pnpm --version
          run: |
            export PATH="/usr/local/cargo/bin:$PATH"
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            pnpm i --registry https://registry.npmjs.org --network-timeout 300000
            pnpm build:napi
            pnpm test
            rm -rf node_modules
            rm -rf target
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bindings-freebsd
          path: ${{ env.APP_NAME }}.*.node

  # build the typescript packages
  build_ts:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm

      - name: build and typecheck
        run: pnpm build

  # Unit test and update coverage report
  unit_test:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm

      - name: run unit tests
        run: pnpm test

  # build the project and run tests on built files.
  build_test:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - 16.x
          - 17.x
      fail-fast: false
    needs:
      - build_napi
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pnpm installation
        uses: ./.github/actions/pnpm
        with:
          node-version: ${{ matrix.node }}

      - name: build project
        run: pnpm build

      - name: run unit tests
        run: pnpm test
