## Listens to the CI workflow and runs the publish command to main when applicable.

name: publish

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  # Publish the project to npm
  npm:
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./.github/actions/pnpm

      - name: download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          path: artifacts
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ci.yml
          workflow_conclusion: success

      - name: move artifacts
        run: pnpm napi:artifacts

      - name: build project
        run: pnpm build

      - name: add token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          pnpm auto shipit
